### ISSUE TITLE
Epic: Blue Book : Chapter 29

### ISSUE THREAD

**Issue by acf** [iamleeg/Amiga-Smalltalk#29]
*Formal Specification of the Primitive Methods*

- [x] Arithmetic Primitives
- [ ] Array and Stream Primitives
- [ ] Storage Management Primitives
- [ ] Control Primitives
- [ ] Input/Output Primitives
- [ ] System Primitives
