### ISSUE TITLE
Epic: Blue Book : Chapter 30

### ISSUE THREAD

**Issue by acf** [iamleeg/Amiga-Smalltalk#30]
*Formal Specification of the Object Memory*

_Heap Storage_
- [x] Compaction

_The Object Table_
- [x] Object Pointers
- [x] Object Table Entries
- [x] Unallocated Space

_Allocation and Deallocation_
- [x] An Allocation Algorithm
- [x] A Deallocation Algorithm
- [x] A Compaction Algorithm

_Garbage Collection_
- [x] A Simple Reference-counting Collector
- [ ] A Space-efficient Reference-counting Collector
- [ ] A Marking Collector

_Nonpointer Objects_
- [ ] CompiledMethods

_Finally_
- [x] Interface to the Bytecode Interpreter
